### PR TITLE
fix(login): reject current login request if existing one is alive

### LINKED ISSUE #3404: Getting Input/output error when trying to access the volume-mount from an application pod
## Description

- Getting Input/output error when trying to access the volume mount across the PODS of a Deployment.
`$ kubectl  exec nginx-deployment-695f8d5d5d-p7zbg -- ls -lh /etc/nginx/conf.d`
`total 0`
`ls: reading directory '/etc/nginx/conf.d': Input/output error`
`command terminated with exit code 2`
  `$ kubectl  exec nginx-deployment-695f8d5d5d-dcfwb -- ls -lh /etc/nginx/conf.d`
   `total 0`
   `ls: reading directory '/etc/nginx/conf.d': Input/output error`
   `command terminated with exit code 2`
Application PODS of the Deployment
```kubectl  get pods
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-695f8d5d5d-nfd5l   1/1     Running   0          4s
nginx-deployment-695f8d5d5d-x7cmk   1/1     Running   0          64s
nginx-deployment-695f8d5d5d-zl6np   1/1     Running   0          3m4s
```
```
kubectl  get deploy
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   3/3     3            3           81m
```
```
kubectl  get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
demo-cstor-vol   Bound    pvc-0680ae85-1a83-4d9e-80c9-1a205f8a28bd   10Gi       RWO            cstor-csi      103m
```

```
$ kubectl  get nodes 
NAME          STATUS   ROLES    AGE    VERSION
portworx-m1   Ready    master   265d   v1.19.2
portworx-w1   Ready    <none>   265d   v1.19.2
portworx-w2   Ready    <none>   265d   v1.19.2
portworx-w3   Ready    <none>   265d   v1.19.2
```
```
$ kubectl  get pods -n openebs --show-labels |grep cspc-operator
cspc-operator-6d796d7b8f-nv4jx                                    1/1     Running   1          2d      name=cspc-operator,openebs.io/component-name=cspc-operator,openebs.io/version=2.9.0,pod-template-hash=6d796d7b8f
```

## Expected Behavior

- The PVC should not be mounted across all the PODS of the deployment and few PODS should go in a Containercreating state.

## Current Behavior

- When the deployment yaml is applied, it creates 3 replicas which is fine as the replica count is 3 in the deployment yaml. But the PVC actually gets mounted across all the PODS and we are able to view the contents of the volume mount. However, this is only possible/stays for few minutes and later start giving as Input/Output error as described in the Description section and expected as well.
```
$ kubectl  exec nginx-deployment-695f8d5d5d-nfd5l  -- ls -lh /etc/nginx/conf.d
total 20K
-rw-r--r-- 1 root root  20 Jun 17 09:24 file
drwx------ 2 root root 16K Jun 17 09:23 lost+found
 
$ kubectl  exec nginx-deployment-695f8d5d5d-x7cmk -- ls -lh /etc/nginx/conf.d
total 20K
-rw-r--r-- 1 root root  20 Jun 17 09:24 file
drwx------ 2 root root 16K Jun 17 09:23 lost+found
```

## Your Environment

* `kubectl get nodes`:
```
$ kubectl  get nodes
NAME          STATUS   ROLES    AGE    VERSION
portworx-m1   Ready    master   265d   v1.19.2
portworx-w1   Ready    <none>   265d   v1.19.2
portworx-w2   Ready    <none>   265d   v1.19.2
portworx-w3   Ready    <none>   265d   v1.19.2
```

* `kubectl get pods --all-namespaces`:
```
$ kubectl  get pods --all-namespaces
NAMESPACE     NAME                                                              READY   STATUS             RESTARTS   AGE
default       nginx-deployment-695f8d5d5d-dcfwb                                 1/1     Running            0          124m
default       nginx-deployment-695f8d5d5d-p7zbg                                 1/1     Running            0          124m
default       nginx-deployment-695f8d5d5d-xpgtr                                 1/1     Running            0          124m
kube-system   autopilot-7c4d5f49d6-jwb48                                        1/1     Running            15         45d
kube-system   coredns-f9fd979d6-2wx4p                                           1/1     Running            6          45d
kube-system   coredns-f9fd979d6-mk655                                           1/1     Running            6          45d
kube-system   etcd-portworx-m1                                                  1/1     Running            20         45d
kube-system   kube-apiserver-portworx-m1                                        1/1     Running            20         45d
kube-system   kube-controller-manager-portworx-m1                               1/1     Running            20         45d
kube-system   kube-proxy-4v7fr                                                  1/1     Running            7          45d
kube-system   kube-proxy-6h7zv                                                  1/1     Running            6          45d
kube-system   kube-proxy-7xwsl                                                  1/1     Running            6          45d
kube-system   kube-proxy-nlmlv                                                  1/1     Running            2          45d
kube-system   kube-router-jqpvz                                                 1/1     Running            8          45d
kube-system   kube-router-mxlkt                                                 1/1     Running            7          45d
kube-system   kube-router-wlmfk                                                 1/1     Running            9          45d
kube-system   kube-router-xzj84                                                 1/1     Running            2          45d
kube-system   kube-scheduler-portworx-m1                                        1/1     Running            20         45d
kube-system   px-lighthouse-777fbbf998-bw2x2                                    3/3     Running   5891       45d
kube-system   stork-7cfcb88895-cxzzn                                            1/1     Running            12         45d
kube-system   stork-7cfcb88895-tqh9t                                            1/1     Running            13         45d
kube-system   stork-7cfcb88895-v9lmh                                            1/1     Running            11         45d
kube-system   stork-scheduler-96d9f4cff-ck4gv                                   1/1     Running            8          45d
kube-system   stork-scheduler-96d9f4cff-j9ks2                                   1/1     Running            6          45d
kube-system   stork-scheduler-96d9f4cff-zvgsw                                   1/1     Running            7          45d
openebs       cspc-operator-6d796d7b8f-nv4jx                                    1/1     Running            1          47h
openebs       cstor-storage-5fxr-679d895884-gxf2k                               3/3     Running            3          46h
openebs       cstor-storage-jskf-bbcd8fcb5-kp9hv                                3/3     Running            3          46h
openebs       cstor-storage-r57t-5d47b8677b-brx7j                               3/3     Running            6          46h
openebs       cvc-operator-849dff65c-cbg2k                                      1/1     Running            2          47h
openebs       openebs-cstor-admission-server-5d868c64d4-xmmjn                   1/1     Running            1          47h
openebs       openebs-cstor-csi-controller-0                                    6/6     Running            6          47h
openebs       openebs-cstor-csi-node-f688q                                      2/2     Running            4          47h
openebs       openebs-cstor-csi-node-gtg67                                      2/2     Running            2          47h
openebs       openebs-cstor-csi-node-qd5p4                                      2/2     Running            2          47h
openebs       openebs-ndm-4rb4f                                                 1/1     Running            2          47h
openebs       openebs-ndm-cjzbg                                                 1/1     Running            3          47h
openebs       openebs-ndm-kr449                                                 1/1     Running            1          47h
openebs       openebs-ndm-operator-59ffcfc949-tcfb9                             1/1     Running            2          47h
openebs       pvc-0680ae85-1a83-4d9e-80c9-1a205f8a28bd-target-69487c985dzppvr   3/3     Running            0          142m
```

* `kubectl get services -n openebs`:
```
openebs       cvc-operator-service                       ClusterIP   10.101.130.91    <none>        5757/TCP                              47h
openebs       openebs-cstor-admission-server             ClusterIP   10.109.186.155   <none>        443/TCP                               47h
openebs       pvc-0680ae85-1a83-4d9e-80c9-1a205f8a28bd   ClusterIP   10.104.206.135   <none>        3260/TCP,7777/TCP,6060/TCP,9500/TCP   144m
```

* `kubectl get sc`:
```
$ kubectl  get sc
NAME                PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
cstor-csi           cstor.csi.openebs.io            Delete          Immediate           true                   46h
mayastor-iscsi      io.openebs.csi-mayastor         Delete          Immediate           false                  217d
mayastor-nvmf       io.openebs.csi-mayastor         Delete          Immediate           false                  217d
mysql-sc            kubernetes.io/portworx-volume   Delete          Immediate           false                  264d
px-ha-sc            kubernetes.io/portworx-volume   Delete          Immediate           false                  264d
stork-snapshot-sc   stork-snapshot                  Delete          Immediate           false                  265d
wordpress-sc        kubernetes.io/portworx-volume   Delete          Immediate           false                  264d
```
* `kubectl get pv`:
```
$ kubectl  get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
pvc-0680ae85-1a83-4d9e-80c9-1a205f8a28bd   10Gi       RWO            Delete           Bound    default/demo-cstor-vol   cstor-csi               146m
```

* `kubectl get pvc`:
```
$ kubectl  get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
demo-cstor-vol   Bound    pvc-0680ae85-1a83-4d9e-80c9-1a205f8a28bd   10Gi       RWO            cstor-csi      147m
```

* OS (from `/etc/os-release`):
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (from `uname -a`):
```
$ uname -a
Linux portworx-m1 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
* Install tools:
* Others:
[TargetPOD-cStor-istgt.txt](https://github.com/openebs/openebs/files/6670157/TargetPOD-cStor-istgt.txt)
[targetpod-maya-volume-exporter.txt](https://github.com/openebs/openebs/files/6670158/targetpod-maya-volume-exporter.txt)
[targetpod-cstor-volume-mgmt.txt](https://github.com/openebs/openebs/files/6670159/targetpod-cstor-volume-mgmt.txt)

* Yamls for SC, PVC,Deployment
```
$ cat sc.yaml 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-csi
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  # cstorPoolCluster should have the name of the CSPC
  cstorPoolCluster: cstor-storage
  # replicaCount should be <= no. of CSPI
  replicaCount: "3"
```

```
$ cat pvc.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-cstor-vol
spec:
  storageClassName: cstor-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

```
cat nginx.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: volumenginx
      volumes:
        - name: volumenginx
          persistentVolumeClaim:
            claimName: demo-cstor-vol
```

### PR DESCRIPTION
**Pull request by mittachaitu**
**What this PR does / why we need it**:
This PR rejects the current login request if an existing connection from
a different initiator is already alive. This check helps to avoid
data corruption by rejecting multiple logins from different initiators.
It also detects the connection break between istgt and iSCSI client
by making use of the [TCP_USER_TIMEOUT](https://man7.org/linux/man-pages/man7/tcp.7.html) setting.
TCP layer will inform the istgt if there is any TCP packet without
acknowledgment for a period(defaults to 120 seconds) of time then
it is treated as connection break b/w client and target.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/3404

**Test Cases**:
### Case1:
- Performing discovery and login operations at the same time from different iSCSI initiators at different time
  - First discovery & login got succeeded
  - Second discovery got failed
     ```sh
     sudo iscsiadm -m discovery -t st -p 10.100.211.24:3260
     iscsiadm: Connection to Discovery Address 10.100.211.24 failed
     iscsiadm: Login I/O error, failed to receive a PDU
     iscsiadm: retrying discovery login to 10.100.211.24
     iscsiadm: Connection to Discovery Address 10.100.211.24 failed
     iscsiadm: Login I/O error, failed to receive a PDU
     iscsiadm: retrying discovery login to 10.100.211.24
     iscsiadm: Connection to Discovery Address 10.100.211.24 failed
     iscsiadm: Login I/O error, failed to receive a PDU
     iscsiadm: retrying discovery login to 10.100.211.24
     iscsiadm: Connection to Discovery Address 10.100.211.24 failed
     iscsiadm: Login I/O error, failed to receive a PDU
     iscsiadm: retrying discovery login to 10.100.211.24
     iscsiadm: Connection to Discovery Address 10.100.211.24 failed
     iscsiadm: Login I/O error, failed to receive a PDU
     iscsiadm: retrying discovery login to 10.100.211.24
     iscsiadm: Connection to Discovery Address 10.100.211.24 failed
     iscsiadm: Login I/O error, failed to receive a PDU
     iscsiadm: retrying discovery login to 10.100.211.24
     iscsiadm: connection login retries (reopen_max) 5 exceeded
     iscsiadm: Could not perform SendTargets discovery: encountered iSCSI login failure
     echo $?
     5
     ```
### Case2:
- Performing discovery and login operation at a different instance of time...
  - Performed discovery from node1 and also perform discovery from node2[both got succeeded]
  - Performed login from node1 and login got succeeded.
  - Performed login from node2 and it got the following error[expected]
  ```sh
   sudo iscsiadm -m node -l
   Logging in to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-7f602321-65d0-4d25-a616-8502176e9d80, portal: 
   10.100.211.24,3260] (multiple)
    iscsiadm: Could not login to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-7f602321-65d0-4d25-a616- 
    8502176e9d80, portal: 10.100.211.24,3260].
    iscsiadm: initiator reported error (11 - iSCSI PDU timed out)
    iscsiadm: Could not log into all portals
    ```
  - On continuation of case2 performed logout from node1 and made login request from node2. It got succeeded.
 
### Case3:
- Perform logins to different target from same node(/initiator)[Should succeeded]
  ```
  [sai@centos-worker-1 2.9.0]$ sudo iscsiadm -m discovery -t st -p 10.100.211.24:3260
  10.100.211.24:3260,1 iqn.2016-09.com.openebs.cstor:pvc-7f602321-65d0-4d25-a616-8502176e9d80
  [sai@centos-worker-1 2.9.0]$ sudo iscsiadm -m discovery -t st -p 10.100.98.73:3260
  10.100.98.73:3260,1 iqn.2016-09.com.openebs.cstor:pvc-ff50d614-d323-473a-b344-8dd7c2ce2237
  [sai@centos-worker-1 2.9.0]$ sudo iscsiadm -m node -l
  Logging in to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-7f602321-65d0-4d25-a616-8502176e9d80, portal: 
  10.100.211.24,3260] (multiple)
  Logging in to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-ff50d614-d323-473a-b344-8dd7c2ce2237, portal: 
  10.100.98.73,3260] (multiple)
  Login to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-7f602321-65d0-4d25-a616-8502176e9d80, portal: 
  10.100.211.24,3260] successful.
  Login to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-ff50d614-d323-473a-b344-8dd7c2ce2237, portal:   
  10.100.98.73,3260] successful.
  ```
### Case4:
- Graceful shutdown of the node where client logged in
  #### On Ubuntu[20.04]/CentOS-7/Ubuntu18.04
  - During shutdown time kernel is sending logout requests to istgt. So connection will be removed
    at target side and if another client performs login from different node things worked in a smooth way.

### Case5:
- Forcible shutdown of the node where client logged in(By force plugging out power)
  #### On Ubuntu[20.04]/CentOS-7
  - istgt receives an event about connection break[EPOLLRDHUP event] after 30seconds(due to tcp_keep_alive probe changes) after losing the connection.
  
  **Note**: 
    -  Above is observed when NopInInterval is set to more than 30 seconds. From my understanding, if the socket is kept busy by writing data at periodic intervals tcp_keep_alive probe is not working as expected because they were given less priority than data packets.
    -  If Nop-In interval is not updated then istgt receives about connection lost only after 15 minutes, this 15minutes is due to `net.ipv4.tcp_retries2 = 15` value... below lines are from man [page](https://linux.die.net/man/7/tcp) of socket.
       ```sh
       tcp_retries2 (integer; default: 15; since Linux 2.2)
       The maximum number of times a TCP packet is retransmitted in an established state before giving up. The default value is 15, 
       which corresponds to a duration of approximately between 13 to 30 minutes, depending on the retransmission timeout. The 
       RFC 1122 specified minimum limit of 100 seconds is typically deemed too short.
       ``` 
  

**Special notes for your reviewer**:
- Changing `net.ipv4.tcp_retries2` value from 15 to 5 istgt able to detect connection break in <30 seconds. This behavior is due to TCP trying to retransmit a packet net.ipv4.retries2 times with exponential back-off time(200ms hardcoded in kernel).
- `tcp_keep_alive` will work like charm in idle connection cases but if a socket is busy and to detect connection break then we may **need to set TCP_USER_TIMEOUT** to ~28sec i.e If there are any unacknowledged packet for 28seconds then TCP will mark connection as broken. 

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has document related information
- [ ] Labelled this PR & related issue with `breaking-changes` tag
- [ ] PR messages has breaking changes related information
- [ ] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] PR messages has upgrade related information
- [ ] Commit has unit tests
- [ ] Commit has integration tests

Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

### CODE REVIEW

File: src/istgt_iscsi.c [hunk 1]
```diff
@@ -7180,6 +7203,42 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
...
+	int i;
+
+	MTX_LOCK(&g_conns_mutex);
+	for (i = 0; i <= g_max_connidx; i++) {
+		existing_conn = g_conns[i];
+		if (existing_conn == NULL)
+			continue;
+		if (existing_conn == conn)
+			continue;
+		// If new connection is totaly different from existing connection
```
Comment (vishnuitta) [inline src/istgt_iscsi.c]: change 'totaly' to 'totally'

File: src/istgt_iscsi.c [hunk 2]
```diff
@@ -7180,6 +7203,42 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
...
+		// then check the status of existing connection if it is active
+		// return true
+		if (strcasecmp(conn->initiator_port, existing_conn->initiator_port) != 0
```
Comment (vishnuitta) [inline src/istgt_iscsi.c]: what is difference between initiator_port and initiator_name?

File: src/istgt_iscsi.c [hunk 3]
```diff
@@ -1965,6 +1966,28 @@ istgt_iscsi_op_login(CONN_Ptr conn, ISCSI_PDU_Ptr pdu)
...
 
+			/* check existing live connections other than current
+			 * initiator. If any of existing connection found live then
+			 * reject the current connection request
+			 */
+			ISTGT_TRACELOG(ISTGT_TRACE_ISCSI,
+				"checking existing live connections "
+				"other than from initiator=%s isid=%"PRIx64", tsih=%u, cid=%u\n",
+				conn->initiator_name, isid, tsih, cid);
+			rc = istgt_iscsi_is_existing_conn_alive(conn);
```
Comment (vishnuitta) [inline src/istgt_iscsi.c]: better to do this only for cstor variant.
consider adding 'REPLICATION' macro

**Comment by vishnuitta** [comment]
consider doing tests for:
- same initiator to multiple targets (this should pass)
- different initiator to same target (should fail)
- same initiator to same target again (this can also pass)
Also, add automated testcases

File: src/istgt_iscsi.c [hunk 4]
```diff
@@ -7180,6 +7203,42 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
...
+			continue;
+		if (existing_conn == conn)
+			continue;
+		// If new connection is totaly different from existing connection
+		// then check the status of existing connection if it is active
+		// return true
+		if (strcasecmp(conn->initiator_port, existing_conn->initiator_port) != 0
+			&& strcasecmp(conn->target_name, existing_conn->target_name) == 0
+			&& strcasecmp(conn->initiator_name, existing_conn->initiator_name) != 0) {
+			if (existing_conn->state == CONN_STATE_RUNNING) {
```
Comment (vishnuitta) [inline src/istgt_iscsi.c]: what are other possible cases? and when does the state gets changed?

File: src/istgt_iscsi.c [hunk 5]
```diff
@@ -7180,6 +7203,42 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
 	return (0);
 }
 
+// istgt_iscsi_is_existing_conn_alive returns 1 if
+// there are any existing connections that are alive
+// else return 0
+static int
+istgt_iscsi_is_existing_conn_alive(CONN_Ptr conn)
```
Comment (vishnuitta) [inline src/istgt_iscsi.c]: any chance of race to reach here for two logins at same time?

File: src/istgt_iscsi.c [hunk 6]
```diff
@@ -7180,6 +7203,42 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
...
+		if (existing_conn == conn)
+			continue;
+		// If new connection is totaly different from existing connection
+		// then check the status of existing connection if it is active
+		// return true
+		if (strcasecmp(conn->initiator_port, existing_conn->initiator_port) != 0
+			&& strcasecmp(conn->target_name, existing_conn->target_name) == 0
+			&& strcasecmp(conn->initiator_name, existing_conn->initiator_name) != 0) {
+			if (existing_conn->state == CONN_STATE_RUNNING) {
+				ISTGT_ERRLOG("connection is already alive from existing initiator=%s (%s) "
```
Comment (vishnuitta) [inline src/istgt_iscsi.c]: there is no need of errlog here. May be, you can print in caller by returning existing_conn details

File: src/istgt_iscsi.c (hunk 2 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: initiator_name is iSCSI client(initator) unique name whereas
`initiator_port` is initiator_name + initiator_session_id(isid)... I think checking for initiator_port over here is no use(I followed from funcs).

**Comment by mittachaitu** [comment]
> consider doing tests for:
> 
> * same initiator to multiple targets (this should pass)
> * different initiator to same target (should fail)
> * same initiator to same target again (this can also pass)
>   Also, add automated testcases

I tried case2 & case3 will try out case1(It should not cause any problem since we made changes on the target side but I will test it out)... Any idea how to simulate case2 in a single node machine?

File: src/istgt_iscsi.c (hunk 4 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: Other possible states exist [here](https://github.com/openebs/istgt/blob/31d7b87a2f8d2fb0f38fbaea12904f30d00f6348/src/istgt_iscsi.h#L181-L186)... 
- Initial state of conn->state is CONN_STATE_INVALID.
- AFAIK after spinning the worker thread(which will get spanned after a client connects to target) & before spinning the sender thread we are marking conn->state to `CONN_STATE_RUNNING`.
- Following are the cases where we mark it as `CONN_STATE_EXITING`
  - When there is an error in target while reading data from an initiator.
  - When the target is not ready to accept IOs.
  - A case where executing opcode got failed.

File: src/istgt_iscsi.c (hunk 5 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: Yes, Since executing opcodes are done by [worker thread](https://github.com/openebs/istgt/blob/replication/src/istgt_iscsi.c#L6628-L6633)(which gets spun after a client connects to target) it is quite possible to have race b/w two different logins from different clients(/initiators). Since we are taking a [global lock-on on g_conns](https://github.com/mittachaitu/istgt/blob/handle_multiple_conns/src/istgt_iscsi.c#L7215) **I thought** it will solve race condition by rejecting current request but the same can happen to another login request also if there is a delay in disconnection from another client (since we are returning non-retryable error)... and this behavior can repeat endlessly. Is my assumption correct?

Comment (mynktl) [reply src/istgt_iscsi.c]: can we introduce new state for this, to avoid race condition?

File: src/istgt_iscsi.c (hunk 2 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: updated the check to compare with initiator_address

File: src/istgt_iscsi.c (hunk 3 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: Updated

File: src/istgt_iscsi.c (hunk 5 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: Pushed this check into istgt_create_conn(there won't be any race)

File: src/istgt_iscsi.c [hunk 7]
```diff
@@ -6506,6 +6508,12 @@ istgt_create_conn(ISTGT_Ptr istgt, PORTAL_Ptr portal, int sock, struct sockaddr
 		goto error_return;
 	}
 
+	rc = set_socket_keepalive(conn->sock);
```
Comment (mynktl) [inline src/istgt_iscsi.c]: requires macro `REPLICATION`

File: src/istgt_iscsi.c [hunk 8]
```diff
@@ -7180,6 +7206,39 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
 	return (0);
 }
 
+// istgt_iscsi_get_existing_live_conn returns existing live
```
Comment (mynktl) [inline src/istgt_iscsi.c:7224]: better to put it under macro `REPLICATION`

File: src/istgt_misc.h [hunk 9]
```diff
@@ -48,6 +48,8 @@
 #include <stddef.h>
 #include <stdio.h>
 
+#include "replication_misc.h"
```
Comment (mynktl) [inline src/istgt_misc.h]: macro `REPLICATION`

File: src/istgt_iscsi.c [hunk 10]
```diff
@@ -5954,7 +5956,7 @@ worker(void *arg)
 // #endif
 
 	events.data.fd = conn->sock;
-	events.events = EPOLLIN;
+	events.events = EPOLLIN | EPOLLHUP | EPOLLRDHUP | EPOLLERR;;
```
Comment (pawanpraka1) [inline src/istgt_iscsi.c]: double ; at the end.

File: src/istgt_iscsi.c [hunk 11]
```diff
@@ -6364,7 +6366,7 @@ int
 istgt_create_conn(ISTGT_Ptr istgt, PORTAL_Ptr portal, int sock, struct sockaddr *sa, socklen_t salen __attribute__((__unused__)))
 {
 	char buf[MAX_TMPBUF];
-	CONN_Ptr conn;
+	CONN_Ptr conn, existing_conn;
```
Comment (pawanpraka1) [inline src/istgt_iscsi.c]: existing_conn should be added for REPLICATION build. Let us move the declaration where it is being used.

File: src/istgt_iscsi.c [hunk 12]
```diff
@@ -7180,6 +7208,41 @@ istgt_iscsi_drop_all_conns(CONN_Ptr conn)
...
+			continue;
+		if (existing_conn == conn)
+			continue;
+		// If new connection is totally different from existing connection
+		// then check the status of existing connection if it is active
+		// return true
+		// Note:
+		//	- Here we are assuming initiator will always use same address for
+		// 	  to interact with iSCSI target
+		//	- Initiator name will get populated only after login request so we
```
Comment (pawanpraka1) [inline src/istgt_iscsi.c:7246]: is it not possible to check this with iqn name? I remember we discussed to move it at login time?

Comment (mittachaitu) [reply src/istgt_iscsi.c:7246]: There exist a race between two different logins... To avoid race we need to add a lot of changes to handle it easily moved before logging time... Since the check is protected by cStor macro I thought we are good.

File: src/istgt_iscsi.c (hunk 7 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: Added `REPLICATION` macro

File: src/istgt_iscsi.c (hunk 8 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c:7224]: updated

File: src/istgt_misc.h (hunk 9 above)
Comment (mittachaitu) [reply src/istgt_misc.h]: Done

File: src/istgt_iscsi.c (hunk 10 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: updated PTAL

File: src/istgt_iscsi.c (hunk 11 above)
Comment (mittachaitu) [reply src/istgt_iscsi.c]: Done

**Review by mynktl — APPROVED** [review]

File: src/istgt.c [hunk 13]
```diff
@@ -1627,6 +1627,17 @@ istgt_init(ISTGT_Ptr istgt)
 	ISTGT_TRACELOG(ISTGT_TRACE_DEBUG, "NopInInterval %d\n",
 	    istgt->nopininterval);
 
+#ifdef REPLICATION
+	int tcpUserTimeoutVal;
+	tcpUserTimeoutVal = istgt_get_intval(sp, "TCPUserTimeout");
+	if (tcpUserTimeoutVal < 0) {
```
Comment (pawanpraka1) [inline src/istgt.c]: make it <=

**Review by pawanpraka1 — COMMENTED** [review]
@mittachaitu do we have a PR for cstor-operators to update the istgt.conf?

**Comment by mittachaitu** [comment]
> @mittachaitu do we have a PR for cstor-operators to update the istgt.conf?

I have [#354](https://github.com/openebs/cstor-operators/pull/354) in openebs/cstor-operators to address it.

**Review by pawanpraka1 — APPROVED** [review]
looks good.

**Review by mynktl — APPROVED** [review]

**Comment by vishnuitta** [comment]
worth to write a blog, and worth to mention reference material as well.
